#!/bin/bash
#
# This file is part of selfrando.
# Copyright (c) 2015-2016 Tommaso Frassetto, TU Darmstadt.
# For license information, see the LICENSE file
# included with selfrando.
#

set -ue

exec 2> >(tee -a /tmp/tc.log >&2)

CC1P="$(which $(gcc -print-prog-name=cc1))"

set -x
exec "$CC1P" "$@" -ffunction-sections -fdata-sections -fPIC
