#!/bin/bash
#
# This file is part of selfrando.
# Copyright (c) 2015-2016 Tommaso Frassetto, TU Darmstadt.
# For license information, see the LICENSE file
# included with selfrando.
#

set -ue

exec 2> >(tee -a /tmp/tc.log >&2)

SR_PATH='/home/debian/install/selfrando'
GOLD="$(which $(gcc -print-prog-name=ld.gold))"

"$SR_PATH/ld.gold" -rpath "$SR_PATH" --traplinker-original-linker "$GOLD" --traplinker-static-selfrando --traplinker-selfrando-txtrp-pages "$@"
