Import('env')

SOURCES = ['symproc.cpp', 'ObjectFileParser.cpp']

debug_defines = {
    # 'MAINprint': 1,
    # 'OFPprintres': 1,
    'OFPreadprint': 1
}

# debugging output
# env = env.Clone(CPPDEFINES = debug_defines)

# not debugging
env = env.Clone()

env.Append(CPPPATH = ['.'])
env.Append(LINKFLAGS = '-static')

if env['TARGET_ARCH'] in ['x86', 'arm']:
    # we need the 32-bit version of SymProc for 32 bit ARM. The easiest way to
    # get this is to just build SymProc as a 32-bit x86 binary, thus including
    # the correct version of the ELF headers for 32-bit ELF.
    env.Append(ASFLAGS = '-m32')
    env.Append(CCFLAGS = '-m32')
    env.Append(LINKFLAGS = '-m32')

files = env.Program('SymProc', SOURCES)
Return('files')
