Import('env')

SOURCES = ['%s/PatchEntry.cpp' % env['PLATFORM']]

env = env.Clone()
if env['PLATFORM'] == 'win32':
    SOURCES.append('win32/stdafx.cpp')

elif env['PLATFORM'] == 'posix':
    env.Append(LIBS = 'elf')
    env.Append(LINKFLAGS = '-static')

# FIXME: for weird reasons, bash&UAC don't like programs named "Patch"
files = env.Program('PatchEntry', SOURCES)
Return('files')
