#!/bin/bash
#
# This file is part of selfrando.
# Copyright (c) 2015-2016 Tommaso Frassetto, TU Darmstadt.
# For license information, see the LICENSE file
# included with selfrando.
#

set -ue

TC_PATH="$(dirname "$0")"
CMD="$(basename "$0")"
export PATH="$(echo $PATH | sed -E 's/^[^:]+://')"

exec "$CMD" "$@" -B"$TC_PATH" -ffunction-sections -fdata-sections
