#!/bin/bash
#
# This file is part of selfrando.
# Copyright (c) 2015-2016 Tommaso Frassetto, TU Darmstadt.
# For license information, see the LICENSE file
# included with selfrando.
#

set -ue

SR_PATH=$(readlink -f "$(dirname "$0")/../../out/x86_64/bin")
GOLD="$(which $(gcc -print-prog-name=ld.gold))"

"$SR_PATH/ld.gold" -rpath "$SR_PATH" --traplinker-original-linker "$GOLD" "$@"
