#!/bin/bash
#
# This file is part of selfrando.
# Copyright (c) 2015-2016 Tommaso Frassetto, TU Darmstadt.
# For license information, see the LICENSE file
# included with selfrando.
#

set -ue

TC_PATH="$(dirname "$0")"
SR_PATH=$(readlink -f "$TC_PATH/../../out/x86_64/bin")
source $TC_PATH/functions.sh

WRAPPER=`basename $0`
ORIG_LD=`find_original`

"$SR_PATH/$WRAPPER" -rpath "$SR_PATH" --traplinker-original-linker "$ORIG_LD" "$@"
